# "events" is a map between Github events and rules.
# possible event names can be seen at https://docs.github.com/en/actions/reference/events-that-trigger-workflows
events:
  # 'pull_request' is the Github event name.
  # '&pull_request' is a YAML anchor
  pull_request: &pull_request
    # Authorize any user when package.json or anything under .github folder was not changed.
    - trustAnyone: true
      paths:
        disallowed:
          - ".github/**"
    
    # # Authorize "bot" user when CHANGELOG.md is the only changed file.
    # - trustedUserNames:
    #     - "bot"
    #   paths:
    #     allowed:
    #       - "CHANGELOG.md"

    # # Authorize collaborators when package.json is the only changed file.
    # - trustCollaborators: true
    #   paths:
    #     allowed:
    #       - "package.json"

  # Reference the "pull_request" anchor to reuse its configuration
  # Read about "pull_request_target" in this blog post:
  # https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
  pull_request_target: *pull_request

  push:
    - trustCollaborators: true

# 'anyEvent' value is a rule, and will be used when an event specific configuration is not set.
# It is automatically added in case it was not explictly set and it does not supports the 'paths' property.
anyEvent:
  trustAnyone: false
  trustCollaborators: false
  trustedUserNames: []