---
name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem-statement
    attributes:
      label: What prompted this feature request?
      description: Is your feature request related to a problem? Please describe.
      placeholder: I get frustrated every time <x> happens, it interrupts my workflow
    validations:
      required: false
  - type: textarea
    id: desired-solution
    attributes:
      label: "Describe the solution you'd like"
      description: A clear and concise description of what you want to happen.
      placeholder: "If we implemented <y>, it would solve my <x> problem."
    validations:
      required: true
  - type: textarea
    id: alternative-solution
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: We could also do <z> and it might solve for <w> and <x>.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/wwt/SwiftCurrent/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
    validations:
      required: false
---
