fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"
    clear_derived_data
  end

  lane :unit_test do
    cocoapods(
      clean: true,
      repo_update: true,
    )
    scan(
      code_coverage: true,
      scheme:  'Workflow',
      workspace: 'Workflow.xcworkspace'
    )
  end
end
