fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"
    clear_derived_data
  end

  lane :unit_test do
    scan(
      code_coverage: true,
      scheme:  'SwiftCurrent',
      workspace: 'SwiftCurrent.xcworkspace',
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
    )
  end

  lane :build_swiftpm do
    sh('swift build --package-path="../" -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"')
    sh('swift build --package-path="../" -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk appletvsimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-tvos14.0-simulator"')
  end

  lane :cocoapods_liblint do
    pod_lib_lint(podspec: 'SwiftCurrent.podspec', allow_warnings: true)
  end

  lane :lint do 
    swiftlint(
      config_file: 'SwiftCurrentLint/.swiftlint.yml',
      raise_if_swiftlint_error: true,
      strict: true
    )
  end

  lane :lintfix do 
    sh('swiftlint --fix --config=../SwiftCurrentLint/.swiftlint.yml')
  end

  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    podspec_name = "SwiftCurrent.podspec"
    version = version_bump_podspec(path: podspec_name,
                                   bump_type: type)
    echo(message: "New Version: #{version}")
    echo(message: "##[set-output name=version;]#{version}")
  end
end