fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"
    clear_derived_data
  end

  lane :unit_test do
    scan(
      code_coverage: true,
      scheme:  'Workflow',
      workspace: 'Workflow.xcworkspace'
    )
  end

  lane :build_swiftpm do
    sh('swift build --package-path="../Workflow" -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"')
  end

  lane :cocoapods_liblint do
    pod_lib_lint(podspec: 'DynamicWorkflow.podspec', allow_warnings: true)
  end

  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    podspec_name = "DynamicWorkflow.podspec"
    version = version_bump_podspec(path: podspec_name,
                                   bump_type: type)
    puts '::set-output name=VERSION::' + version
    update_plist(
      plist_path: "Workflow/Info.plist",
      block: proc do |plist|
        plist[:CFBundleVersion] = version
      end
    )
  end
end